// Sri Lankan EV Market Data
export const evModels = [
  {
    id: 1,
    brand: 'Tesla',
    model: 'Model 3',
    variant: 'Standard Range Plus',
    year: 2024,
    price: 16500000,
    image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
    type: 'Sedan',
    batteryCapacity: 60,
    range: 420,
    acceleration: 5.3,
    topSpeed: 225,
    chargingTime: { ac: 8, dc: 0.5 },
    seatingCapacity: 5,
    features: ['Autopilot', 'Premium Audio', 'Glass Roof', 'Heated Seats'],
    efficiency: 140,
    warranty: '8 years / 160,000 km battery',
    availability: 'Available',
    importDuty: 25,
  },
  {
    id: 2,
    brand: 'Nissan',
    model: 'Leaf',
    variant: 'e+',
    year: 2023,
    price: 8500000,
    image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800',
    type: 'Hatchback',
    batteryCapacity: 62,
    range: 385,
    acceleration: 6.9,
    topSpeed: 157,
    chargingTime: { ac: 11.5, dc: 0.75 },
    seatingCapacity: 5,
    features: ['ProPILOT Assist', 'e-Pedal', 'NissanConnect', 'LED Headlights'],
    efficiency: 161,
    warranty: '8 years / 160,000 km battery',
    availability: 'Available',
    importDuty: 20,
  },
  {
    id: 3,
    brand: 'BYD',
    model: 'Atto 3',
    variant: 'Standard',
    year: 2024,
    price: 9800000,
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800',
    type: 'SUV',
    batteryCapacity: 60.5,
    range: 420,
    acceleration: 7.3,
    topSpeed: 160,
    chargingTime: { ac: 9, dc: 0.5 },
    seatingCapacity: 5,
    features: ['Adaptive Cruise Control', '360° Camera', 'Panoramic Sunroof', 'Wireless Charging'],
    efficiency: 144,
    warranty: '6 years / 150,000 km battery',
    availability: 'Available',
    importDuty: 20,
  },
  {
    id: 4,
    brand: 'MG',
    model: 'ZS EV',
    variant: 'Excite',
    year: 2023,
    price: 7200000,
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800',
    type: 'SUV',
    batteryCapacity: 51,
    range: 320,
    acceleration: 8.2,
    topSpeed: 175,
    chargingTime: { ac: 8.5, dc: 0.67 },
    seatingCapacity: 5,
    features: ['Leather Seats', 'Touchscreen Infotainment', 'Rear Camera', 'Keyless Entry'],
    efficiency: 159,
    warranty: '7 years / 150,000 km battery',
    availability: 'Available',
    importDuty: 18,
  },
  {
    id: 5,
    brand: 'Hyundai',
    model: 'Ioniq 5',
    variant: 'Long Range',
    year: 2024,
    price: 13500000,
    image: 'https://images.unsplash.com/photo-1617886322235-ef09e0b75e6c?w=800',
    type: 'SUV',
    batteryCapacity: 77.4,
    range: 507,
    acceleration: 7.4,
    topSpeed: 185,
    chargingTime: { ac: 7, dc: 0.3 },
    seatingCapacity: 5,
    features: ['V2L', 'Digital Cockpit', 'Head-Up Display', 'Smart Parking'],
    efficiency: 153,
    warranty: '8 years / 160,000 km battery',
    availability: 'Pre-Order',
    importDuty: 22,
  },
  {
    id: 6,
    brand: 'Kia',
    model: 'EV6',
    variant: 'GT-Line',
    year: 2024,
    price: 14200000,
    image: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800',
    type: 'SUV',
    batteryCapacity: 77.4,
    range: 528,
    acceleration: 5.2,
    topSpeed: 185,
    chargingTime: { ac: 7.5, dc: 0.3 },
    seatingCapacity: 5,
    features: ['800V Charging', 'Augmented Reality HUD', 'Remote Parking', 'Premium Sound'],
    efficiency: 147,
    warranty: '7 years / 150,000 km battery',
    availability: 'Available',
    importDuty: 22,
  },
];

export const chargingStations = [
  {
    id: 1,
    name: 'CEB Colombo Central',
    location: 'Colombo 01',
    coordinates: [6.9271, 79.8612],
    type: 'Public',
    chargerTypes: ['AC', 'DC Fast'],
    power: ['7.4 kW', '50 kW'],
    available: 4,
    total: 6,
    price: 45,
    amenities: ['Parking', 'WiFi', 'Restrooms'],
    hours: '24/7',
  },
  {
    id: 2,
    name: 'LECO Nugegoda Station',
    location: 'Nugegoda',
    coordinates: [6.8649, 79.8997],
    type: 'Public',
    chargerTypes: ['AC'],
    power: ['7.4 kW'],
    available: 2,
    total: 3,
    price: 40,
    amenities: ['Parking', 'Security'],
    hours: '8:00 AM - 8:00 PM',
  },
  {
    id: 3,
    name: 'Arpico Supercentre Kandy',
    location: 'Kandy',
    coordinates: [7.2906, 80.6337],
    type: 'Semi-Public',
    chargerTypes: ['AC', 'DC Fast'],
    power: ['11 kW', '60 kW'],
    available: 3,
    total: 4,
    price: 48,
    amenities: ['Parking', 'Shopping', 'Food Court'],
    hours: '9:00 AM - 10:00 PM',
  },
  {
    id: 4,
    name: 'Galle Face Green Station',
    location: 'Colombo 03',
    coordinates: [6.9271, 79.8456],
    type: 'Public',
    chargerTypes: ['AC', 'DC Fast'],
    power: ['7.4 kW', '50 kW'],
    available: 5,
    total: 8,
    price: 45,
    amenities: ['Parking', 'Scenic View', 'Cafe'],
    hours: '24/7',
  },
  {
    id: 5,
    name: 'CEB Gampaha Hub',
    location: 'Gampaha',
    coordinates: [7.0873, 79.9990],
    type: 'Public',
    chargerTypes: ['AC'],
    power: ['7.4 kW'],
    available: 1,
    total: 2,
    price: 38,
    amenities: ['Parking'],
    hours: '7:00 AM - 7:00 PM',
  },
  {
    id: 6,
    name: 'Majestic City Colombo',
    location: 'Bambalapitiya',
    coordinates: [6.8905, 79.8563],
    type: 'Semi-Public',
    chargerTypes: ['AC'],
    power: ['11 kW'],
    available: 2,
    total: 3,
    price: 50,
    amenities: ['Parking', 'Shopping', 'Cinema', 'Food Court'],
    hours: '10:00 AM - 10:00 PM',
  },
];
